[package]
name = "rx-operating-area-judge"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"
[workspace]
[dependencies]
rx-package = {path="../../crates/rx-package"}
rx-storage = {path="../../crates/rx-storage"}
rx-domain = {path="../../crates/rx-domain"}
serde_json = "1"
uuid = {version="1",features=["v4"]}
tempfile = "3"
