[package]
name = "rx-protocol-adapter"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
rx-application = { path = "../rx-application" }
rx-domain = { path = "../rx-domain" }
rx-protocol = { path = "../rx-protocol" }
tonic.workspace = true

[lints]
workspace = true
