[package]
name = "rx-platformd"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
rx-package = {path="../rx-package"}
rx-api = {path="../rx-api"}
rx-host-client = {path="../rx-host-client"}
rx-application = {path="../rx-application"}
rx-domain = {path="../rx-domain"}
rx-ports = {path="../rx-ports"}
rx-runtime = {path="../rx-runtime"}
rx-storage = {path="../rx-storage"}
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid = {workspace=true,features=["v4"]}
tokio = {version="1",features=["rt-multi-thread","macros","signal","net","time","sync"]}
tempfile.workspace = true
[target.'cfg(target_os = "linux")'.dependencies]
rustix = {version="1.1.4",features=["time"]}
[lints]
workspace = true

[dev-dependencies]
rx-process-contract = {path="../rx-process-contract"}
ed25519-dalek = "3"
rcgen = "0.14"
reqwest = {version="0.12",default-features=false,features=["json","rustls-tls-manual-roots"]}
rx-protocol = {path="../rx-protocol"}
tonic.workspace = true
