use rx_domain::component::{Binding, Registration};
use serde_json::{Value, json};

// Published supervisor v1 document shapes, supplied as input rather than generated by the
// types under test. Storage envelopes remain owned by the application and supervisor.
fn registration() -> Value {
    json!({
        "id": "00000000-0000-4000-8000-000000000001",
        "declaration": {"label": "sensor", "catalog": {
            "program": "rx/status-http",
            "digest": "0000000000000000000000000000000000000000000000000000000000000000"
        }},
        "state": "ACCEPTED"
    })
}

#[test]
fn supervisor_v1_registration_and_binding_keep_their_representation() {
    for state in ["ACCEPTED", "RETIRED"] {
        let mut legacy = registration();
        legacy["state"] = json!(state);
        let decoded: Registration = serde_json::from_value(legacy.clone()).unwrap();
        assert_eq!(serde_json::to_value(decoded).unwrap(), legacy);
    }
    let legacy = json!({
        "registration": "00000000-0000-4000-8000-000000000001",
        "registration_revision": "9007199254740993",
        "catalog": registration()["declaration"]["catalog"],
        "run": "00000000-0000-4000-8000-000000000002",
        "selection": "observation",
        "instance": "00000000-0000-4000-8000-000000000003"
    });
    let decoded: Binding = serde_json::from_value(legacy.clone()).unwrap();
    assert_eq!(serde_json::to_value(decoded).unwrap(), legacy);
}

#[test]
fn registration_cannot_smuggle_execution_ownership_or_work_permission() {
    for field in [
        "pid",
        "execution_ownership",
        "functional_readiness",
        "work_use_permission",
    ] {
        let mut input = registration();
        input[field] = json!(true);
        assert!(serde_json::from_value::<Registration>(input).is_err());
    }
}
