#!/usr/bin/env python3
"""Reviewed field transcription of the frozen RX v1 tables; emits IDL and semantic aliases.

No field numbers are allocated implicitly for existing contract message types.
Cell RPC request wrappers use the numbering explicitly specified by cell §4.
Run this script and check the resulting diff; it is not run during Cargo builds.
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "proto"
ALIASES = {"Id": "string", "Name": "string", "Digest": "bytes", "UtcTime": "string"}
RULES = {}


def snake(s):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", s).upper()


class Schema:
    def __init__(self, package, filename, imports=()):
        self.package = package
        self.filename = filename
        self.lines = ['syntax = "proto3";', f"package {package};"]
        self.lines += [f'import "{p}";' for p in imports]
        self.lines += ["// Generated by tools/generate_protocol.py. Preserve contract field numbers.", ""]

    def typ(self, typ):
        if typ.startswith("base."):
            suffix = typ[5:]
            return ALIASES.get(suffix, "rx.contract.v1." + suffix)
        if self.package == "rx.cell.v1" and typ in ("TimePoint", "ArtifactRef", "CallContext", "Evidence", "Receipt", "Grant"):
            return "rx.contract.v1." + typ
        return ALIASES.get(typ, typ)

    def enum(self, name, names):
        prefix = snake(name)
        tokens = ["UNSPECIFIED", *names.split(",")]
        self.lines += [f"enum {name} {{"]
        self.lines += [f"  {prefix}_{token.strip()} = {i};" for i, token in enumerate(tokens)]
        self.lines += ["}", ""]

    def message(self, name, fields, oneof=None):
        self.lines += [f"message {name} {{"]
        if oneof:
            self.lines += [f"  oneof {oneof} {{"]
        for field in fields.split():
            field_name, spec = field.split(":")
            typ, num = spec.split("#")
            modifier = ""
            if typ.endswith("[]"):
                modifier, typ = "repeated ", typ[:-2]
            elif typ.endswith("?"):
                modifier, typ = "optional ", typ[:-1]
            self.lines += [f"  {'  ' if oneof else ''}{modifier}{self.typ(typ)} {field_name} = {num};"]
            RULES[f"{self.package}.{name}.{field_name}"] = typ.removeprefix("base.")
        if oneof:
            self.lines += ["  }"]
        self.lines += ["}", ""]

    def service(self, name, methods):
        # Session and Evidence are both message and logical service names in the prose.
        self.lines += [f"service {name}Service {{"]
        for method, input_, output in methods:
            stream = output.startswith("stream ")
            output = output.removeprefix("stream ")
            input_type = self.typ(input_)
            output_type = self.typ(output)
            input_type = "." + (input_type if "." in input_type else self.package + "." + input_type)
            output_type = "." + (output_type if "." in output_type else self.package + "." + output_type)
            self.lines += [f"  rpc {method} ({input_type}) returns ({'stream ' if stream else ''}{output_type});"]
        self.lines += ["}", ""]

    def write(self):
        path = OUT / self.filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(self.lines))


b = Schema("rx.contract.v1", "rx/contract/v1/contract.proto")
for name, tokens in {
    "Role": "PLATFORM,EXECUTOR,HOST,OPERATOR_API",
    "Kind": "FINITE_ACTION,ENSURE_STATE,MODE_TRANSITION,CONTROL_SESSION,LIFECYCLE_TRANSITION",
    "Phase": "ADMITTED,ACTIVE,RECONCILING,SETTLED",
    "Knowledge": "NOT_SENT,MAY_HAVE_EXECUTED,ACCEPTED,RUNNING,ENDED,UNKNOWN",
    "Outcome": "NONE,SUCCEEDED,FAILED,CANCELED,NOT_EXECUTED,UNRESOLVED",
    "Integrity": "VALID,DISPUTED",
    "Disposition": "HELD,QUARANTINED,RELEASED",
    "LifecycleVerb": "PREPARE,ACTIVATE,DEACTIVATE,SHUTDOWN",
    "ReceiptStage": "ADMITTED,HOST_PREPARED,SEND_ENTERED,NATIVE_ACCEPTED,RESULT_RECORDED,NOT_DISPATCHED",
    "HostReceiptState": "PREPARED,SEND_ENTERED,NATIVE_REJECTED,NATIVE_ACCEPTED,RESULT_CAPTURED,VOIDED_BEFORE_SEND",
    "Quality": "GOOD,UNCERTAIN,BAD",
    "FreshnessBasis": "SOURCE_SAMPLE,PACKET_RECEIPT,READ_TRANSACTION,CACHED_UNKNOWN",
    "ControlState": "OPENING,OPEN,CLOSING,CLOSED",
    "RunState": "PREPARED,EXECUTING,PAUSED,RECOVERY_REQUIRED,COMPLETED,ABANDONED",
    "FindingCode": "SATISFIED,PACKAGE_MISSING,MODEL_MISMATCH,MODE_MISMATCH,CALIBRATION_INVALID,EVIDENCE_UNAVAILABLE,TIMING_UNVALIDATED,AUTHORITY_UNAVAILABLE",
    "EventType": "OPERATION_ADMITTED,HOST_RECEIPT_RECORDED,EVIDENCE_RECORDED,OPERATION_REVISED,CANCEL_REQUESTED,RESOURCE_REVISED,RUN_REVISED,RELEASE_REVISED,INTEGRITY_DISPUTED,RECOVERY_DISPOSITION_RECORDED",
    "ReasonCode": "OK,INVALID_ARGUMENT,UNAUTHENTICATED,FORBIDDEN,KEY_CONFLICT,REVISION_CONFLICT,BUSY,UNSUPPORTED_SCHEMA,CAPABILITY_MISSING,PRECONDITION_FAILED,STALE_AUTHORITY,EXPIRED,UNKNOWN_OUTCOME,NOT_FOUND,GAP,CURSOR_EXPIRED,SNAPSHOT_EXPIRED,SLOW_CONSUMER,STORE_FAULT,INTEGRITY_CONFLICT,ALREADY_SETTLED,RESOURCE_EXHAUSTED",
    "RetryAction": "NONE,FIX_REQUEST,AUTHENTICATE,INSPECT_EXISTING,REFRESH,RETRY_SAME_KEY,CHANGE_RELEASE,RECONFIGURE,RECONCILE,REACQUIRE,REPLAY,SNAPSHOT",
}.items():
    b.enum(name, tokens)

for name, fields in {
    "TimePoint": "clock_id:string#1 ticks_ns:uint64#2",
    "ArtifactRef": "sha256:Digest#1 schema_id:Name#2 size_bytes:uint64#3",
    "Version": "major:uint32#1 minor:uint32#2 schema_hash:Digest#3",
    "PeerHello": "peer_id:Name#1 role:Role#2 boot_id:Id#3 installation_id:Id#4 store_generation:Id#5 supported_versions:Version[]#6 release_digest:Digest#7 journal_id:Id?#8 last_seq:uint64?#9 shared_clock_id:string#10",
    "Session": "session_id:Id#1 peer_id:Name#2 boot_id:Id#3 selected_version:Version#4 required_features:Name[]#5 limits:Limits#6",
    "CallContext": "session_id:Id#1 call_id:Id#2 request_key:string?#3 expected_revision:uint64?#4",
    "SubmitOperation": "context:CallContext#1 intent:Intent#2 run_id:Id?#3 activation_id:Id?#4 slot:Name?#5",
    "Intent": "kind:Kind#1 target:Name#2 profile_digest:Digest#3 site_config_digest:Digest#4 calibration_digests:Digest[]#5 resource_set:Name[]#6 execution_timeout_ms:uint64#7 prepare_validity_ms:uint64#8 completion_rule:Name#9 cancel_rule:Name#10 body:Body#11",
    "TrajectoryGoal": "trajectory:ArtifactRef#1 joint_group:Name#2 tool_digest:Digest#3",
    "ProgramGoal": "program:ArtifactRef#1 parameter_set:ArtifactRef#2",
    "PredicateGoal": "predicate_id:Name#1 target:TypedValue#2 settle_ms:uint64#3",
    "ModeGoal": "mode_id:Name#1 transition_profile:Digest#2",
    "ControlGoal": "source_id:Name#1 sample_schema:Name#2 stream_profile:Digest#3",
    "LifecycleGoal": "transition:LifecycleVerb#1 target_level:Name#2 support_evidence:Id[]#3",
    "RealVector": "values:double[]#1",
    "Receipt": "operation_id:Id#1 intent_digest:Digest#2 operation_revision:uint64?#3 stage:ReceiptStage#4 invocation_id:Id?#5 journal_id:Id#6 journal_seq:uint64#7 host_state:HostReceiptState?#8 cancel_id:Id?#9",
    "OperationView": "operation_id:Id#1 revision:uint64#2 intent_digest:Digest#3 phase:Phase#4 execution_knowledge:Knowledge#5 outcome:Outcome#6 integrity:Integrity#7 disposition:Disposition#8 evidence_ids:Id[]#9 reason:Reason#10 control_state:ControlState?#11 cancel_ids:Id[]#12",
    "OperationRef": "context:CallContext#1 operation_id:Id#2",
    "CancelRequest": "context:CallContext#1 operation_id:Id#2 cancel_rule:Name#3 reason:Reason#4 intent_digest:Digest#5 cancel_id:Id?#6",
    "GrantRequest": "context:CallContext#1 resource_set:Name[]#2 fence:uint64#3 owner_id:Name#4 requested_ttl_ms:uint64#5",
    "Grant": "grant_id:Id#1 host_boot_id:Id#2 fence:uint64#3 resource_set:Name[]#4 ttl_ms:uint64#5 owner_id:Name#6",
    "RenewGrant": "context:CallContext#1 grant_id:Id#2 renew_seq:uint64#3",
    "PrepareOperation": "context:CallContext#1 operation_id:Id#2 intent:Intent#3 intent_digest:Digest#4 grant:Grant#5",
    "AuthorizeDispatch": "context:CallContext#1 operation_id:Id#2 invocation_id:Id#3 intent_digest:Digest#4 grant:Grant#5",
    "Observation": "observation_id:Id#1 source_id:Name#2 source_boot_evidence:string?#3 receive_boot_id:Id#4 receive_time:TimePoint#5 sample_seq:uint64?#6 source_time:TimePoint?#7 quality:Quality#8 value_schema:Name#9 value:TypedValue#10 correlation:Correlation#11 freshness_basis:FreshnessBasis#12 uncertainty_ms:uint64?#13",
    "Correlation": "operation_id:Id?#1 invocation_id:Id?#2 native_id:string?#3 device_session_id:Id#4 profile_digest:Digest#5 cancel_id:Id?#6",
    "Evidence": "evidence_id:Id#1 evidence_schema:Name#2 profile_digest:Digest#3 body:EvidenceBody#4",
    "NativeResult": "correlation:Correlation#1 native_status_schema:Name#2 native_status:sint64#3 native_data:ArtifactRef?#4 captured_at:TimePoint#5",
    "Attestation": "actor_id:Name#1 procedure_digest:Digest#2 assertion_id:Name#3 value:TypedValue#4 observed_at:UtcTime#5 scope:Name[]#6",
    "EvidenceBatch": "context:CallContext#1 producer_journal_id:Id#2 first_seq:uint64#3 records:Evidence[]#4",
    "DurableAck": "producer_journal_id:Id#1 through_seq:uint64#2 platform_cursor:Cursor#3",
    "Event": "event_id:Id#1 cursor:Cursor#2 event_type:EventType#3 operation_id:Id?#4 entity_revision:uint64#5 evidence_ids:Id[]#6 entity:EntityView#7",
    "Cursor": "installation_id:Id#1 store_generation:Id#2 seq:uint64#3 view_id:Name#4",
    "Snapshot": "snapshot_id:Id#1 through:Cursor#2 entities:EntityView[]#3 continuation:string?#4",
    "SubscribeRequest": "context:CallContext#1 after:Cursor#2 max_batch:uint32#3",
    "EvidenceRef": "context:CallContext#1 evidence_id:Id#2",
    "ObservationQuery": "context:CallContext#1 source_ids:Name[]#2 value_schemas:Name[]#3",
    "ObservationBatch": "observations:Observation[]#1 dropped_count:uint64#2",
    "Limits": "max_message_bytes:uint32#1 max_batch_records:uint32#2 subscriber_buffer_bytes:uint32#3 max_inflight:uint32#4",
    "Reason": "code:ReasonCode#1 detail:string?#2 related_ids:Id[]#3",
    "ErrorDetail": "reason:Reason#1 retry_action:RetryAction#2 operation_id:Id?#3 expected_revision:uint64?#4 earliest_cursor:Cursor?#5 next_expected_seq:uint64?#6",
    "RunView": "run_id:Id#1 revision:uint64#2 recipe_digest:Digest#3 state:RunState#4 checkpoint:Checkpoint#5 executor_session_id:Id?#6",
    "Checkpoint": "run_id:Id#1 revision:uint64#2 executor_schema:Name#3 payload:ArtifactRef#4 activations:ActivationView[]#5",
    "ActivationView": "activation_id:Id#1 node_id:Name#2 visit:uint64#3 slots:SlotBinding[]#4",
    "SlotBinding": "slot:Name#1 operation_id:Id#2 intent_digest:Digest#3",
    "ResourceView": "resource_id:Name#1 revision:uint64#2 fence:uint64#3 disposition:Disposition#4 owner_id:Name?#5 hold_reason:Reason#6",
    "ReleaseView": "release_digest:Digest#1 site_config_digest:Digest#2 revision:uint64#3 admitted_profiles:Digest[]#4 rejected_profiles:ProfileFinding[]#5",
    "ProfileFinding": "profile:Digest#1 reason:Reason#2 finding:FindingCode#3 support_id:Name#4",
    "ChangeCheckpoint": "context:CallContext#1 run_id:Id#2 expected_revision:uint64#3 new_checkpoint:Checkpoint#4",
    "ResolveActivation": "context:CallContext#1 run_id:Id#2 node_id:Name#3 visit:uint64#4",
    "EvaluateProfile": "context:CallContext#1 target:Name#2 profile_digest:Digest#3 site_config_digest:Digest#4",
    "ProfileEvaluation": "findings:ProfileFinding[]#1 release_view:ReleaseView#2",
    "SnapshotPageRequest": "context:CallContext#1 snapshot_id:Id#2 continuation:string#3",
    "RevokeGrantRequest": "context:CallContext#1 grant_id:Id#2 new_fence:uint64#3 reason:Reason#4",
    "RunRequest": "context:CallContext#1 run_id:Id?#2 recipe_digest:Digest#3 site_config_digest:Digest#4",
    "RecoveryDisposition": "context:CallContext#1 operation_id:Id#2 expected_revision:uint64#3 evidence_ids:Id[]#4 procedure_digest:Digest#5 disposition:Disposition#6 reason:Reason#7",
    "StreamTicket": "ticket_id:Id#1 session_id:Id#2 host_boot_id:Id#3 valid_for_ms:uint64#4",
    "ControlSample": "session_id:Id#1 source_boot_id:Id#2 source_seq:uint64#3 ticket:StreamTicket#4 values:TypedValue#5 source_evidence_ids:Id[]#6",
    "GrantRevocation": "grant_id:Id#1 new_fence:uint64#2 evidence_ids:Id[]#3 reason:Reason#4",
}.items():
    b.message(name, fields)

b.message("Body", "trajectory:TrajectoryGoal#1 program:ProgramGoal#2 predicate:PredicateGoal#3 mode:ModeGoal#4 control:ControlGoal#5 lifecycle:LifecycleGoal#6", "value")
b.message("TypedValue", "boolean:bool#1 integer:sint64#2 real:double#3 symbol:Name#4 reals:RealVector#5", "value")
b.message("EvidenceBody", "observation:Observation#1 native_result:NativeResult#2 attestation:Attestation#3", "value")
b.message("EntityView", "operation:OperationView#1 run:RunView#2 resource:ResourceView#3 release:ReleaseView#4", "value")
b.service("Session", [("Open", "PeerHello", "Session")])
b.service("Operation", [(m, i, o) for m, i, o in [
    ("Submit","SubmitOperation","Receipt"),("Get","OperationRef","OperationView"),("Lookup","CallContext","Receipt"),
    ("RequestCancel","CancelRequest","OperationView"),("Reconcile","OperationRef","OperationView")]])
b.service("Recovery", [("RecordDisposition","RecoveryDisposition","OperationView")])
b.service("Workflow", [(m,"RunRequest","RunView") for m in ["CreateRun","StartRun","PauseRun","AbandonRun","GetRun"]] +
    [("ResolveActivation","ResolveActivation","ActivationView"),("CommitCheckpoint","ChangeCheckpoint","RunView")])
b.service("Admission", [("EvaluateProfile","EvaluateProfile","ProfileEvaluation")])
b.service("Host", [
    ("AcquireGrant","GrantRequest","Grant"),("RenewGrant","RenewGrant","Grant"),
    ("PrepareOperation","PrepareOperation","Receipt"),("AuthorizeDispatch","AuthorizeDispatch","Receipt"),
    ("GetReceipt","OperationRef","Receipt"),("GetCancelReceipt","CancelRequest","Receipt"),
    ("CancelOperation","CancelRequest","Receipt"),("Reconcile","OperationRef","EvidenceBatch"),
    ("WatchObservations","ObservationQuery","stream ObservationBatch"),
    ("RevokeGrant","RevokeGrantRequest","GrantRevocation"),("CloseControlSession","CancelRequest","Receipt"),
    ("NextStreamTicket","OperationRef","StreamTicket"),("PushSample","ControlSample","Reason")])
b.service("Evidence", [("Publish","EvidenceBatch","DurableAck"),("Get","EvidenceRef","Evidence")])
b.service("Journal", [("GetSnapshot","SubscribeRequest","Snapshot"),("GetSnapshotPage","SnapshotPageRequest","Snapshot"),("Subscribe","SubscribeRequest","stream Event")])
b.write()

c = Schema("rx.cell.v1", "rx/cell/v1/cell.proto", ["rx/contract/v1/contract.proto"])
for name, tokens in {
    "OperatingMode": "SETUP,AUTOMATIC,RECOVERY,MAINTENANCE",
    "Commissioning": "NOT_COMMISSIONED,COMMISSIONED,REVALIDATION_REQUIRED",
    "QualificationState": "DRAFT,IN_REVIEW,QUALIFIED,SUSPENDED,RETIRED",
    "Verdict": "PASS,FAIL,UNKNOWN", "BlockKind": "TRANSIENT,LATCHED",
    "StartOrigin": "OPERATOR,BATCH_SCHEDULER", "Purpose": "PRODUCTION,SETUP,RECOVERY",
    "MandateState": "ACTIVE,REVOKED,EXHAUSTED,CLOSED", "BudgetUnit": "PART_ATTEMPT,OPERATION_COUNT",
    "PartDisposition": "IN_PROGRESS,CONFIRMED_COMPLETED,REJECTED,UNRESOLVED,NOT_PROCESSED",
    "PermitState": "ISSUED,CONSUMED,VOIDED,EXPIRED", "StartStatus": "PENDING,ARMING,STARTED,REJECTED",
    "CaseType": "DIAGNOSTIC_ONLY,PLANNED_ACCESS,FAULT_RECOVERY,MAINTENANCE,CHANGE_REVIEW",
    "CaseState": "OPEN,CONTAINMENT_PENDING,PROCEDURE_ACTIVE,REVALIDATING,READY_FOR_RESTART,CLOSED,ESCALATED",
    "ProcedureAction": "ACKNOWLEDGE,ENTRY_CONDITIONS_REPORTED,WORK_STARTED,WORK_FINISHED,PERSONNEL_ACCOUNTED,ISOLATION_STATE_REPORTED,RESET_OBSERVED,HANDOVER_ACCEPTED,CONFIGURATION_REPORTED",
    "ChangeState": "PROPOSED,IMPACT_REVIEWED,STAGED,APPLIED_UNQUALIFIED,QUALIFIED_ACTIVE",
    "ClearanceDisposition": "RESTART,REMAIN_OUT_OF_SERVICE",
    "IdentityBasis": "VERIFIED_SENSOR,TRACKED_SLOT,HUMAN_DECLARED,UNKNOWN_IDENTITY",
    "PreparationState": "PENDING_FENCE,REVALIDATING,READY,REJECTED",
    "CellReason": "NONE,NOT_COMMISSIONED,OUTSIDE_ENVELOPE,QUALIFICATION_REQUIRED,CONDITION_FAILED,CONDITION_UNKNOWN,BLOCKED_BY_CASE,STALE_EPOCH,MANDATE_REVOKED,BUDGET_EXHAUSTED,PERMIT_EXPIRED,PERMIT_CONSUMED,CONTINUITY_UNPROVEN,CLEARANCE_STALE,PERSONNEL_UNACCOUNTED,EXTERNAL_RESTRICTION,NATIVE_EFFECT_UNRESOLVED,MIXED_CONFIGURATION,UPGRADE_REQUIRED,STALE_REVISION,KEY_CONFLICT,FORBIDDEN,STORE_FAULT,INVALID_INPUT",
    "CellEventType": "CONTEXT_CHANGED,QUALIFICATION_CHANGED,MANDATE_CHANGED,PERMIT_CHANGED,START_CHANGED,CASE_CHANGED,PROCEDURE_RECORDED,CLEARANCE_CHANGED,MATERIAL_CHANGED,CHANGE_RECORDED,PART_ATTEMPT_CHANGED,PREPARATION_CHANGED",
}.items():
    c.enum(name, tokens)

for name, fields in {
    "CellHello": "base_manifest_hash:Digest#1 cell_manifest_hash:Digest#2 peer_id:Name#3 base_session_id:Id#4 cell_definition_digest:Digest#5 shared_clock_id:string#6",
    "CellSession": "session_id:Id#1 base_session_id:Id#2 peer_id:Name#3 manifest_hash:Digest#4",
    "CellCall": "context:CallContext#1 cell_id:Name#2 expected_cell_revision:uint64?#3",
    "ScopeEpoch": "scope_id:Name#1 epoch:uint64#2",
    "CellRef": "cell_id:Name#1 cell_epoch:uint64#2 scopes:ScopeEpoch[]#3",
    "CellContext": "cell_id:Name#1 revision:uint64#2 cell_epoch:uint64#3 scopes:ScopeEpoch[]#4 definition:ArtifactRef#5 envelope:ArtifactRef#6 qualification_id:Id?#7 mode:OperatingMode#8 blocks:Block[]#9 open_case_ids:Id[]#10 commissioning:Commissioning#11",
    "Qualification": "qualification_id:Id#1 revision:uint64#2 envelope:ArtifactRef#3 state:QualificationState#4 evidence:ArtifactRef[]#5 dependency_hashes:Digest[]#6 reviewed_by:Name[]#7 limitations:ArtifactRef#8",
    "ConditionEvaluation": "condition_id:Name#1 condition_revision:uint64#2 verdict:Verdict#3 reason:CellReason#4 evidence_ids:Id[]#5 evaluated_at:TimePoint#6 valid_until:TimePoint#7 cell:CellRef#8",
    "Block": "block_id:Id#1 kind:BlockKind#2 reason:CellReason#3 scope_ids:Name[]#4 condition_id:Name?#5 case_id:Id?#6 created_revision:uint64#7",
    "RunMandate": "mandate_id:Id#1 run_id:Id#2 cell:CellRef#3 envelope_digest:Digest#4 actor:Name#5 origin:StartOrigin#6 purpose:Purpose#7 state:MandateState#8 budget:RunBudget#9 executor_session_id:Id#10 start_attempt_id:Id#11 restart_plan:ArtifactRef?#12",
    "RunBudget": "unit:BudgetUnit#1 limit:uint64#2 consumed:uint64#3 revision:uint64#4",
    "PartAttempt": "part_attempt_id:Id#1 run_id:Id#2 ordinal:uint64#3 material_id:Id?#4 revision:uint64#5 disposition:PartDisposition#6",
    "DispatchPermit": "permit_id:Id#1 operation_id:Id#2 intent_digest:Digest#3 cell:CellRef#4 envelope_digest:Digest#5 qualification_id:Id#6 qualification_revision:uint64#7 purpose:Purpose#8 parent:PermitParent#9 grant:base.Grant#10 host_boot_id:Id#11 issued_at:TimePoint#12 expires_at:TimePoint#13 conditions:ConditionEvaluation[]#14 state:PermitState#15",
    "RecoveryStepRef": "case_id:Id#1 plan:ArtifactRef#2 step_id:Name#3 visit:uint64#4",
    "CaseRevision": "case_id:Id#1 revision:uint64#2",
    "StartAttempt": "attempt_id:Id#1 run_id:Id#2 status:StartStatus#3 target:CellRef#4 expected_cell_revision:uint64#5 case_revisions:CaseRevision[]#6 clearance_ids:Id[]#7 mandate_id:Id?#8 reason:CellReason#9",
    "InterventionCase": "case_id:Id#1 revision:uint64#2 cell:CellRef#3 type:CaseType#4 state:CaseState#5 procedure:ArtifactRef#6 lead:Name#7 participants:Name[]#8 operation_ids:Id[]#9 material_ids:Id[]#10 record_ids:Id[]#11 block_ids:Id[]#12",
    "ProcedureRecord": "record_id:Id#1 case_id:Id#2 case_revision:uint64#3 action:ProcedureAction#4 actor:Name#5 scope_ids:Name[]#6 occurred_at:base.UtcTime#7 evidence_ids:Id[]#8 assertions:ArtifactRef#9",
    "Clearance": "clearance_id:Id#1 case_revisions:CaseRevision[]#2 cell:CellRef#3 evidence_ids:Id[]#4 prepared_at:TimePoint#5 valid_until:TimePoint#6 disposition:ClearanceDisposition#7 consumed_by:Id?#8 target_run_id:Id?#9 envelope_digest:Digest#10 restart_plan:ArtifactRef?#11",
    "SupportClaim": "holder:Name#1 verdict:Verdict#2 evidence_ids:Id[]#3 valid_until:TimePoint#4",
    "MaterialState": "material_id:Id#1 revision:uint64#2 identity_basis:IdentityBasis#3 identity_evidence:Id[]#4 location_claim:Name?#5 supports:SupportClaim[]#6 scope:CellRef#7",
    "ChangeRecord": "change_id:Id#1 revision:uint64#2 cell:CellRef#3 before:ArtifactRef[]#4 after:ArtifactRef[]#5 state:ChangeState#6 affected_ids:Name[]#7 evidence_ids:Id[]#8 applied_by:Name?#9",
    "EvaluationSet": "evaluations:ConditionEvaluation[]#1 cell:CellRef#2",
    "RestartPreparation": "preparation_id:Id#1 target:CellRef#2 status:PreparationState#3 clearance:Clearance?#4 reason:CellReason#5",
    "HostCellState": "cell:CellRef#1 host_boot_id:Id#2 block_ids:Id[]#3 pending_operation_ids:Id[]#4 pending_permit_ids:Id[]#5 definition_digest:Digest#6",
    "FenceReceipt": "target:CellRef#1 invalidation_id:Id#2 host_boot_id:Id#3 delivery_journal_id:Id#4 seq:uint64#5",
    "ArmReceipt": "target:CellRef#1 attempt_id:Id#2 host_boot_id:Id#3 delivery_journal_id:Id#4 seq:uint64#5",
    "CellEvent": "event_id:Id#1 type:CellEventType#2 entity:CellEntity#3",
    "CellError": "code:CellReason#1 cell:CellRef?#2 block_ids:Id[]#3 case_ids:Id[]#4 evidence_ids:Id[]#5 detail:string?#6",
}.items():
    c.message(name, fields)
c.message("PermitParent", "mandate_id:Id#1 recovery:RecoveryStepRef#2", "value")
c.message("CellEntity", "context:CellContext#1 qualification:Qualification#2 mandate:RunMandate#3 permit:DispatchPermit#4 start:StartAttempt#5 case:InterventionCase#6 procedure:ProcedureRecord#7 clearance:Clearance#8 material:MaterialState#9 change:ChangeRecord#10 part_attempt:PartAttempt#11 preparation:RestartPreparation#12", "value")
# Mixed envelope has a cursor plus a true oneof.
c.lines += ["message CellJournalRecord {", "  rx.contract.v1.Cursor cursor = 1;", "  oneof body {", "    rx.contract.v1.Event base_event = 2;", "    CellEvent cell_event = 3;", "  }", "}", ""]
RULES["rx.cell.v1.CellJournalRecord.cursor"] = "Cursor"
RULES["rx.cell.v1.CellJournalRecord.base_event"] = "Event"
RULES["rx.cell.v1.CellJournalRecord.cell_event"] = "CellEvent"

methods = []
for method, fields, output in [
    ("Evaluate","operation_intent:base.Intent parent:PermitParent","EvaluationSet"),
    ("StartRun","run_id:Id envelope_digest:Digest purpose:Purpose budget_unit:BudgetUnit budget_limit:uint64 origin:StartOrigin","StartAttempt"),
    ("GetStartAttempt","attempt_id:Id","StartAttempt"),
    ("BeginPartAttempt","run_id:Id mandate_id:Id expected_budget_revision:uint64","PartAttempt"),
    ("SubmitOperation","request:base.SubmitOperation parent:PermitParent part_attempt_id:Id? expected_run_revision:uint64? expected_case_revision:uint64?","base.Receipt"),
    ("Hold","scope_ids:Name[] reason:CellReason condition_ids:Name[]","CellContext"),
    ("ClearTransientBlock","block_ids:Id[] evidence_ids:Id[]","CellContext"),
    ("OpenCase","type:CaseType scopes:Name[] procedure:ArtifactRef lead:Name operation_ids:Id[] material_ids:Id[]","InterventionCase"),
    ("RecordProcedure","expected_case_revision:uint64 record:ProcedureRecord","InterventionCase"),
    ("SetRecoveryPlan","case_id:Id expected_case_revision:uint64 plan:ArtifactRef","InterventionCase"),
    ("PrepareRestart","case_revisions:CaseRevision[] target_run_id:Id restart_plan:ArtifactRef","RestartPreparation"),
    ("GetRestartPreparation","preparation_id:Id","RestartPreparation"),
    ("PrepareClose","case_revisions:CaseRevision[] evidence_ids:Id[]","Clearance"),
    ("RestartRun","run_id:Id clearance_id:Id expected_run_revision:uint64","StartAttempt"),
    ("CloseWithoutRestart","case_revisions:CaseRevision[] clearance_id:Id","CellContext"),
    ("RecordChange","change:ChangeRecord","ChangeRecord"),
    ("RegisterQualification","qualification:Qualification","Qualification"),
    ("GetCase","case_id:Id","InterventionCase"),
    ("GetMaterial","material_id:Id","MaterialState"),
]:
    c.message(method+"Request", "call:CellCall#1 " + " ".join(f"{field}#{i}" for i, field in enumerate(fields.split(), 2)))
    methods.append((method, method+"Request", output))
c.service("Cell", [("Open","CellHello","CellSession"),("Inspect","CellCall","CellContext"),*methods])

host_methods = [("Inspect","CellCall","HostCellState")]
for method, fields, output in [
    ("FenceCell","target:CellRef block_ids:Id[] invalidation_id:Id","FenceReceipt"),
    ("ArmCell","attempt_id:Id target:CellRef clearance_ids:Id[] block_ids_to_clear:Id[]","ArmReceipt"),
    ("Prepare","base_request:base.PrepareOperation permit:DispatchPermit","base.Receipt"),
    ("Authorize","base_request:base.AuthorizeDispatch permit:DispatchPermit","base.Receipt"),
]:
    c.message("Host"+method+"Request", "call:CellCall#1 " + " ".join(f"{field}#{i}" for i, field in enumerate(fields.split(), 2)))
    host_methods.append((method, "Host"+method+"Request", output))
c.service("CellHost", host_methods)
# Snapshot payload uses a wrapper oneof because protobuf cannot repeat a oneof directly.
c.message("SnapshotEntity", "base_entity:base.EntityView#1 cell_entity:CellEntity#2", "value")
c.message("CellSnapshot", "snapshot_id:Id#1 through:base.Cursor#2 entities:SnapshotEntity[]#3 continuation:string?#4")
c.service("CellJournal", [
    ("GetSnapshot","base.SubscribeRequest","CellSnapshot"),
    ("GetSnapshotPage","base.SnapshotPageRequest","CellSnapshot"),
    ("Subscribe","base.SubscribeRequest","stream CellJournalRecord")])
c.write()
# Optional release-specific executor read binding. It does not replace frozen mutations.
e = Schema("rx.executor.v1", "rx/executor/v1/executor.proto", ("rx/contract/v1/contract.proto",))
e.message("SnapshotRequest", "context:base.CallContext#1 run_id:Id#2 visit:uint64#3 binding_hash:Digest#4")
e.message("ArtifactRequest", "context:base.CallContext#1 run_id:Id#2 reference:base.ArtifactRef#3 binding_hash:Digest#4")
e.message("ReadPayload", "reference:base.ArtifactRef#1 payload:bytes#2")
e.service("ExecutorRead", [("GetSnapshot","SnapshotRequest","ReadPayload"),("GetArtifact","ArtifactRequest","ReadPayload")])
e.write()
# Optional preparation binding. State changes still use frozen Workflow.CommitCheckpoint.
p = Schema("rx.executor.plan.v1", "rx/executor/plan/v1/plan.proto", ("rx/contract/v1/contract.proto",))
p.enum("CheckpointAction", "CHOOSE_BRANCH,START_WAIT,CHECK_WAIT")
p.enum("PreparationState", "READY,WAITING,ALREADY_APPLIED")
p.message("PrepareCheckpoint", "context:base.CallContext#1 run_id:Id#2 node_id:Name#3 visit:uint64#4 action:CheckpointAction#5 binding_hash:Digest#6")
p.message("CheckpointPreparation", "state:PreparationState#1 expected_revision:uint64#2 checkpoint:base.Checkpoint?#3 prepared_at:base.TimePoint?#4 valid_until:base.TimePoint?#5")
p.service("ExecutorPlan", [("PrepareCheckpoint", "PrepareCheckpoint", "CheckpointPreparation")])
p.write()
# Optional production coordination: frozen BeginPartAttempt is reused for admission.
r = Schema("rx.executor.production.v1", "rx/executor/production/v1/production.proto", ("rx/contract/v1/contract.proto", "rx/cell/v1/cell.proto", "rx/executor/v1/executor.proto"))
r.message("InspectRun", "context:base.CallContext#1 run_id:Id#2 binding_hash:Digest#3")
r.message("CompletePart", "context:base.CallContext#1 cell_id:Name#2 run_id:Id#3 part_attempt_id:Id#4 expected_run_revision:uint64#5 expected_part_revision:uint64#6 binding_hash:Digest#7")
r.service("Production", [("Inspect", "InspectRun", "rx.executor.v1.ReadPayload"), ("CompletePart", "CompletePart", "rx.cell.v1.PartAttempt")])
r.write()
# Optional executor assignment discovery, independent from existing production v1.
a = Schema("rx.executor.assignment.v1", "rx/executor/assignment/v1/assignment.proto", ("rx/contract/v1/contract.proto", "rx/executor/v1/executor.proto"))
a.message("InspectCell", "context:base.CallContext#1 cell_id:Name#2 binding_hash:Digest#3")
a.service("ExecutorAssignment", [("Inspect", "InspectCell", "rx.executor.v1.ReadPayload")])
a.write()
# Optional Host bootstrap/state read binding; no new native write surface.
h = Schema("rx.host.read.v1", "rx/host/read/v1/read.proto", ("rx/contract/v1/contract.proto", "rx/cell/v1/cell.proto"))
h.message("InspectHost", "call:rx.cell.v1.CellCall#1 source_ids:Name[]#2 binding_hash:Digest#3")
h.message("HostPayload", "reference:base.ArtifactRef#1 payload:bytes#2")
h.service("HostRead", [("Inspect", "InspectHost", "HostPayload")])
h.write()
# Optional process-context acceptance; native reconfiguration remains a separate contract.
g = Schema("rx.host.configuration.v1", "rx/host/configuration/v1/configuration.proto", ("rx/contract/v1/contract.proto", "rx/cell/v1/cell.proto"))
g.message("InspectConfiguration", "context:base.CallContext#1 binding_hash:Digest#2")
g.message("ApplyConfiguration", "call:rx.cell.v1.CellCall#1 binding_hash:Digest#2 reference:base.ArtifactRef#3 payload:bytes#4")
g.message("LookupConfiguration", "context:base.CallContext#1 request_id:Id#2 binding_hash:Digest#3")
g.message("ConfigurationPayload", "reference:base.ArtifactRef#1 payload:bytes#2")
g.service("HostConfiguration", [("Inspect", "InspectConfiguration", "ConfigurationPayload"),("Apply", "ApplyConfiguration", "ConfigurationPayload"),("Lookup", "LookupConfiguration", "ConfigurationPayload")])

g.write()

g = Schema("rx.host.qualification.v1", "rx/host/qualification/v1/qualification.proto", ("rx/contract/v1/contract.proto", "rx/cell/v1/cell.proto"))
g.message("InspectQualification", "context:base.CallContext#1 binding_hash:Digest#2")
g.message("AcceptQualification", "call:rx.cell.v1.CellCall#1 binding_hash:Digest#2 reference:base.ArtifactRef#3 payload:bytes#4")
g.message("LookupQualification", "context:base.CallContext#1 request_id:Id#2 binding_hash:Digest#3")
g.message("QualificationPayload", "reference:base.ArtifactRef#1 payload:bytes#2")
g.service("HostQualification", [("Inspect", "InspectQualification", "QualificationPayload"),("Accept", "AcceptQualification", "QualificationPayload"),("Lookup", "LookupQualification", "QualificationPayload")])
g.write()

(OUT / "semantic_fields.json").write_text(json.dumps(RULES, sort_keys=True, indent=2) + "\n")
print(f"Wrote base/cell and optional executor schemas and {len(RULES)} semantic field mappings")
